name: utilities
description: To hold utility classes for projects.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  cloud_firestore: ^4.0.2
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
