name: firestore_repository
description: Flutter package which manages the data domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  cloud_firestore: ^4.0.2
  equatable: ^2.0.5
  firebase_core: ^2.1.0
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  meta: ^1.8.0

dev_dependencies:
  cloud_firestore_platform_interface: ^5.8.2
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^3.1.0
