name: authentication_repository
version: 0.1.0+1
publish_to: none
description: Dart package which manages the authentication domain.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^4.0.2
  firebase_auth_platform_interface: ^6.10.4
  firebase_core: ^2.1.0
  firestore_repository:
    path: ../firestore_repository
  flutter:
    sdk: flutter
  meta: ^1.8.0
  models:
    path: ../models

dev_dependencies:
  firebase_core_platform_interface: ^4.5.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^3.1.0
