name: form_inputs
description: Set of form-inputs which can be re-used across an application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  formz: ^0.4.1
  models:
    path: ../models

dev_dependencies:
  test: ^1.19.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
